title: Project
'@extends':
    type: main
    context: theme://blueprints

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:

            columns:
              type: columns
              fields:

                column1:
                  type: column
                  fields:

                    header.subtitle:
                      style: vertical
                      type: textarea
                      rows: 3
                      label: Subtitle

                    header.website:
                      style: vertical
                      type: text
                      label: Website

        details:
          type: tab
          title: Детали
          ordering@: 1
          fields:
            header.opportunities:
              name: opportunities
              type: list
              label: Возможности
              style: vertical

              fields:
                .verb:
                  type: text
                  label: Глагол
                .text:
                  type: text
                  label: Текст
                .link:
                  type: text
                  label: Link
