title: Project
'@extends':
    type: mainpro
    context: theme://blueprints

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        details:
          type: tab
          title: Детали
          ordering@: 1
          fields:
            header.opportunities:
              name: opportunities
              type: list
              label: Возможности
              style: vertical

              fields:
                .verb:
                  type: text
                  label: Глагол
                .text:
                  type: text
                  label: Текст
                .link:
                  type: text
                  label: Link
